title: "RIFE: Real-Time Intermediate Flow Estimation for Video Frame Interpolation"
description: RIFE is a video frame interpolation algorithm that runs in real-time speed
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  paper_url: https://arxiv.org/abs/2011.06294
  git_url: https://github.com/hzwer/arXiv2020-RIFE
demo:
  vid1_id: kUQ7KK6MhHw
