title: "RIFE: Real-Time Intermediate Flow Estimation for Video Frame Interpolation"
description: [Zhewei Huang](https://scholar.google.com/citations?user=zJEkaG8AAAAJ&hl=en), [Tianyuan Zhang](http://tianyuanzhang.com/), Wen Heng, [Boxin Shi](http://ci.idm.pku.edu.cn/), [Shuchang Zhou](https://zsc.github.io/)
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  paper_url: https://arxiv.org/abs/2011.06294
  git_url: https://github.com/hzwer/arXiv2020-RIFE
demo:
  vid1_id: kUQ7KK6MhHw
